-- Countries: drop code/flag_emoji, add flag_url, seed all countries with flag images
alter table public.countries drop column if exists code;
alter table public.countries drop column if exists flag_emoji;
alter table public.countries add column if not exists flag_url text;

insert into public.countries (name, flag_url, status) values
  ('Afghanistan', 'https://flagcdn.com/w80/af.png', 'active'),
  ('Albania', 'https://flagcdn.com/w80/al.png', 'active'),
  ('Algeria', 'https://flagcdn.com/w80/dz.png', 'active'),
  ('Andorra', 'https://flagcdn.com/w80/ad.png', 'active'),
  ('Angola', 'https://flagcdn.com/w80/ao.png', 'active'),
  ('Antigua and Barbuda', 'https://flagcdn.com/w80/ag.png', 'active'),
  ('Argentina', 'https://flagcdn.com/w80/ar.png', 'active'),
  ('Armenia', 'https://flagcdn.com/w80/am.png', 'active'),
  ('Australia', 'https://flagcdn.com/w80/au.png', 'active'),
  ('Austria', 'https://flagcdn.com/w80/at.png', 'active'),
  ('Azerbaijan', 'https://flagcdn.com/w80/az.png', 'active'),
  ('Bahamas', 'https://flagcdn.com/w80/bs.png', 'active'),
  ('Bahrain', 'https://flagcdn.com/w80/bh.png', 'active'),
  ('Bangladesh', 'https://flagcdn.com/w80/bd.png', 'active'),
  ('Barbados', 'https://flagcdn.com/w80/bb.png', 'active'),
  ('Belarus', 'https://flagcdn.com/w80/by.png', 'active'),
  ('Belgium', 'https://flagcdn.com/w80/be.png', 'active'),
  ('Belize', 'https://flagcdn.com/w80/bz.png', 'active'),
  ('Benin', 'https://flagcdn.com/w80/bj.png', 'active'),
  ('Bhutan', 'https://flagcdn.com/w80/bt.png', 'active'),
  ('Bolivia', 'https://flagcdn.com/w80/bo.png', 'active'),
  ('Bosnia and Herzegovina', 'https://flagcdn.com/w80/ba.png', 'active'),
  ('Botswana', 'https://flagcdn.com/w80/bw.png', 'active'),
  ('Brazil', 'https://flagcdn.com/w80/br.png', 'active'),
  ('Brunei', 'https://flagcdn.com/w80/bn.png', 'active'),
  ('Bulgaria', 'https://flagcdn.com/w80/bg.png', 'active'),
  ('Burkina Faso', 'https://flagcdn.com/w80/bf.png', 'active'),
  ('Burundi', 'https://flagcdn.com/w80/bi.png', 'active'),
  ('Cambodia', 'https://flagcdn.com/w80/kh.png', 'active'),
  ('Cameroon', 'https://flagcdn.com/w80/cm.png', 'active'),
  ('Canada', 'https://flagcdn.com/w80/ca.png', 'active'),
  ('Cape Verde', 'https://flagcdn.com/w80/cv.png', 'active'),
  ('Central African Republic', 'https://flagcdn.com/w80/cf.png', 'active'),
  ('Chad', 'https://flagcdn.com/w80/td.png', 'active'),
  ('Chile', 'https://flagcdn.com/w80/cl.png', 'active'),
  ('China', 'https://flagcdn.com/w80/cn.png', 'active'),
  ('Colombia', 'https://flagcdn.com/w80/co.png', 'active'),
  ('Comoros', 'https://flagcdn.com/w80/km.png', 'active'),
  ('Congo', 'https://flagcdn.com/w80/cg.png', 'active'),
  ('Costa Rica', 'https://flagcdn.com/w80/cr.png', 'active'),
  ('Croatia', 'https://flagcdn.com/w80/hr.png', 'active'),
  ('Cuba', 'https://flagcdn.com/w80/cu.png', 'active'),
  ('Cyprus', 'https://flagcdn.com/w80/cy.png', 'active'),
  ('Czechia', 'https://flagcdn.com/w80/cz.png', 'active'),
  ('Denmark', 'https://flagcdn.com/w80/dk.png', 'active'),
  ('Djibouti', 'https://flagcdn.com/w80/dj.png', 'active'),
  ('Dominica', 'https://flagcdn.com/w80/dm.png', 'active'),
  ('Dominican Republic', 'https://flagcdn.com/w80/do.png', 'active'),
  ('Ecuador', 'https://flagcdn.com/w80/ec.png', 'active'),
  ('Egypt', 'https://flagcdn.com/w80/eg.png', 'active'),
  ('El Salvador', 'https://flagcdn.com/w80/sv.png', 'active'),
  ('Equatorial Guinea', 'https://flagcdn.com/w80/gq.png', 'active'),
  ('Eritrea', 'https://flagcdn.com/w80/er.png', 'active'),
  ('Estonia', 'https://flagcdn.com/w80/ee.png', 'active'),
  ('Eswatini', 'https://flagcdn.com/w80/sz.png', 'active'),
  ('Ethiopia', 'https://flagcdn.com/w80/et.png', 'active'),
  ('Fiji', 'https://flagcdn.com/w80/fj.png', 'active'),
  ('Finland', 'https://flagcdn.com/w80/fi.png', 'active'),
  ('France', 'https://flagcdn.com/w80/fr.png', 'active'),
  ('Gabon', 'https://flagcdn.com/w80/ga.png', 'active'),
  ('Gambia', 'https://flagcdn.com/w80/gm.png', 'active'),
  ('Georgia', 'https://flagcdn.com/w80/ge.png', 'active'),
  ('Germany', 'https://flagcdn.com/w80/de.png', 'active'),
  ('Ghana', 'https://flagcdn.com/w80/gh.png', 'active'),
  ('Greece', 'https://flagcdn.com/w80/gr.png', 'active'),
  ('Grenada', 'https://flagcdn.com/w80/gd.png', 'active'),
  ('Guatemala', 'https://flagcdn.com/w80/gt.png', 'active'),
  ('Guinea', 'https://flagcdn.com/w80/gn.png', 'active'),
  ('Guinea-Bissau', 'https://flagcdn.com/w80/gw.png', 'active'),
  ('Guyana', 'https://flagcdn.com/w80/gy.png', 'active'),
  ('Haiti', 'https://flagcdn.com/w80/ht.png', 'active'),
  ('Honduras', 'https://flagcdn.com/w80/hn.png', 'active'),
  ('Hungary', 'https://flagcdn.com/w80/hu.png', 'active'),
  ('Iceland', 'https://flagcdn.com/w80/is.png', 'active'),
  ('India', 'https://flagcdn.com/w80/in.png', 'active'),
  ('Indonesia', 'https://flagcdn.com/w80/id.png', 'active'),
  ('Iran', 'https://flagcdn.com/w80/ir.png', 'active'),
  ('Iraq', 'https://flagcdn.com/w80/iq.png', 'active'),
  ('Ireland', 'https://flagcdn.com/w80/ie.png', 'active'),
  ('Israel', 'https://flagcdn.com/w80/il.png', 'active'),
  ('Italy', 'https://flagcdn.com/w80/it.png', 'active'),
  ('Ivory Coast', 'https://flagcdn.com/w80/ci.png', 'active'),
  ('Jamaica', 'https://flagcdn.com/w80/jm.png', 'active'),
  ('Japan', 'https://flagcdn.com/w80/jp.png', 'active'),
  ('Jordan', 'https://flagcdn.com/w80/jo.png', 'active'),
  ('Kazakhstan', 'https://flagcdn.com/w80/kz.png', 'active'),
  ('Kenya', 'https://flagcdn.com/w80/ke.png', 'active'),
  ('Kiribati', 'https://flagcdn.com/w80/ki.png', 'active'),
  ('Kuwait', 'https://flagcdn.com/w80/kw.png', 'active'),
  ('Kyrgyzstan', 'https://flagcdn.com/w80/kg.png', 'active'),
  ('Laos', 'https://flagcdn.com/w80/la.png', 'active'),
  ('Latvia', 'https://flagcdn.com/w80/lv.png', 'active'),
  ('Lebanon', 'https://flagcdn.com/w80/lb.png', 'active'),
  ('Lesotho', 'https://flagcdn.com/w80/ls.png', 'active'),
  ('Liberia', 'https://flagcdn.com/w80/lr.png', 'active'),
  ('Libya', 'https://flagcdn.com/w80/ly.png', 'active'),
  ('Liechtenstein', 'https://flagcdn.com/w80/li.png', 'active'),
  ('Lithuania', 'https://flagcdn.com/w80/lt.png', 'active'),
  ('Luxembourg', 'https://flagcdn.com/w80/lu.png', 'active'),
  ('Madagascar', 'https://flagcdn.com/w80/mg.png', 'active'),
  ('Malawi', 'https://flagcdn.com/w80/mw.png', 'active'),
  ('Malaysia', 'https://flagcdn.com/w80/my.png', 'active'),
  ('Maldives', 'https://flagcdn.com/w80/mv.png', 'active'),
  ('Mali', 'https://flagcdn.com/w80/ml.png', 'active'),
  ('Malta', 'https://flagcdn.com/w80/mt.png', 'active'),
  ('Marshall Islands', 'https://flagcdn.com/w80/mh.png', 'active'),
  ('Mauritania', 'https://flagcdn.com/w80/mr.png', 'active'),
  ('Mauritius', 'https://flagcdn.com/w80/mu.png', 'active'),
  ('Mexico', 'https://flagcdn.com/w80/mx.png', 'active'),
  ('Micronesia', 'https://flagcdn.com/w80/fm.png', 'active'),
  ('Moldova', 'https://flagcdn.com/w80/md.png', 'active'),
  ('Monaco', 'https://flagcdn.com/w80/mc.png', 'active'),
  ('Mongolia', 'https://flagcdn.com/w80/mn.png', 'active'),
  ('Montenegro', 'https://flagcdn.com/w80/me.png', 'active'),
  ('Morocco', 'https://flagcdn.com/w80/ma.png', 'active'),
  ('Mozambique', 'https://flagcdn.com/w80/mz.png', 'active'),
  ('Myanmar', 'https://flagcdn.com/w80/mm.png', 'active'),
  ('Namibia', 'https://flagcdn.com/w80/na.png', 'active'),
  ('Nauru', 'https://flagcdn.com/w80/nr.png', 'active'),
  ('Nepal', 'https://flagcdn.com/w80/np.png', 'active'),
  ('Netherlands', 'https://flagcdn.com/w80/nl.png', 'active'),
  ('New Zealand', 'https://flagcdn.com/w80/nz.png', 'active'),
  ('Nicaragua', 'https://flagcdn.com/w80/ni.png', 'active'),
  ('Niger', 'https://flagcdn.com/w80/ne.png', 'active'),
  ('Nigeria', 'https://flagcdn.com/w80/ng.png', 'active'),
  ('North Korea', 'https://flagcdn.com/w80/kp.png', 'active'),
  ('North Macedonia', 'https://flagcdn.com/w80/mk.png', 'active'),
  ('Norway', 'https://flagcdn.com/w80/no.png', 'active'),
  ('Oman', 'https://flagcdn.com/w80/om.png', 'active'),
  ('Pakistan', 'https://flagcdn.com/w80/pk.png', 'active'),
  ('Palau', 'https://flagcdn.com/w80/pw.png', 'active'),
  ('Palestine', 'https://flagcdn.com/w80/ps.png', 'active'),
  ('Panama', 'https://flagcdn.com/w80/pa.png', 'active'),
  ('Papua New Guinea', 'https://flagcdn.com/w80/pg.png', 'active'),
  ('Paraguay', 'https://flagcdn.com/w80/py.png', 'active'),
  ('Peru', 'https://flagcdn.com/w80/pe.png', 'active'),
  ('Philippines', 'https://flagcdn.com/w80/ph.png', 'active'),
  ('Poland', 'https://flagcdn.com/w80/pl.png', 'active'),
  ('Portugal', 'https://flagcdn.com/w80/pt.png', 'active'),
  ('Qatar', 'https://flagcdn.com/w80/qa.png', 'active'),
  ('Romania', 'https://flagcdn.com/w80/ro.png', 'active'),
  ('Russia', 'https://flagcdn.com/w80/ru.png', 'active'),
  ('Rwanda', 'https://flagcdn.com/w80/rw.png', 'active'),
  ('Saint Kitts and Nevis', 'https://flagcdn.com/w80/kn.png', 'active'),
  ('Saint Lucia', 'https://flagcdn.com/w80/lc.png', 'active'),
  ('Saint Vincent and the Grenadines', 'https://flagcdn.com/w80/vc.png', 'active'),
  ('Samoa', 'https://flagcdn.com/w80/ws.png', 'active'),
  ('San Marino', 'https://flagcdn.com/w80/sm.png', 'active'),
  ('Sao Tome and Principe', 'https://flagcdn.com/w80/st.png', 'active'),
  ('Saudi Arabia', 'https://flagcdn.com/w80/sa.png', 'active'),
  ('Senegal', 'https://flagcdn.com/w80/sn.png', 'active'),
  ('Serbia', 'https://flagcdn.com/w80/rs.png', 'active'),
  ('Seychelles', 'https://flagcdn.com/w80/sc.png', 'active'),
  ('Sierra Leone', 'https://flagcdn.com/w80/sl.png', 'active'),
  ('Singapore', 'https://flagcdn.com/w80/sg.png', 'active'),
  ('Slovakia', 'https://flagcdn.com/w80/sk.png', 'active'),
  ('Slovenia', 'https://flagcdn.com/w80/si.png', 'active'),
  ('Solomon Islands', 'https://flagcdn.com/w80/sb.png', 'active'),
  ('Somalia', 'https://flagcdn.com/w80/so.png', 'active'),
  ('South Africa', 'https://flagcdn.com/w80/za.png', 'active'),
  ('South Korea', 'https://flagcdn.com/w80/kr.png', 'active'),
  ('South Sudan', 'https://flagcdn.com/w80/ss.png', 'active'),
  ('Spain', 'https://flagcdn.com/w80/es.png', 'active'),
  ('Sri Lanka', 'https://flagcdn.com/w80/lk.png', 'active'),
  ('Sudan', 'https://flagcdn.com/w80/sd.png', 'active'),
  ('Suriname', 'https://flagcdn.com/w80/sr.png', 'active'),
  ('Sweden', 'https://flagcdn.com/w80/se.png', 'active'),
  ('Switzerland', 'https://flagcdn.com/w80/ch.png', 'active'),
  ('Syria', 'https://flagcdn.com/w80/sy.png', 'active'),
  ('Taiwan', 'https://flagcdn.com/w80/tw.png', 'active'),
  ('Tajikistan', 'https://flagcdn.com/w80/tj.png', 'active'),
  ('Tanzania', 'https://flagcdn.com/w80/tz.png', 'active'),
  ('Thailand', 'https://flagcdn.com/w80/th.png', 'active'),
  ('Timor-Leste', 'https://flagcdn.com/w80/tl.png', 'active'),
  ('Togo', 'https://flagcdn.com/w80/tg.png', 'active'),
  ('Tonga', 'https://flagcdn.com/w80/to.png', 'active'),
  ('Trinidad and Tobago', 'https://flagcdn.com/w80/tt.png', 'active'),
  ('Tunisia', 'https://flagcdn.com/w80/tn.png', 'active'),
  ('Turkey', 'https://flagcdn.com/w80/tr.png', 'active'),
  ('Turkmenistan', 'https://flagcdn.com/w80/tm.png', 'active'),
  ('Tuvalu', 'https://flagcdn.com/w80/tv.png', 'active'),
  ('Uganda', 'https://flagcdn.com/w80/ug.png', 'active'),
  ('Ukraine', 'https://flagcdn.com/w80/ua.png', 'active'),
  ('United Arab Emirates', 'https://flagcdn.com/w80/ae.png', 'active'),
  ('United Kingdom', 'https://flagcdn.com/w80/gb.png', 'active'),
  ('United States', 'https://flagcdn.com/w80/us.png', 'active'),
  ('Uruguay', 'https://flagcdn.com/w80/uy.png', 'active'),
  ('Uzbekistan', 'https://flagcdn.com/w80/uz.png', 'active'),
  ('Vanuatu', 'https://flagcdn.com/w80/vu.png', 'active'),
  ('Vatican City', 'https://flagcdn.com/w80/va.png', 'active'),
  ('Venezuela', 'https://flagcdn.com/w80/ve.png', 'active'),
  ('Vietnam', 'https://flagcdn.com/w80/vn.png', 'active'),
  ('Yemen', 'https://flagcdn.com/w80/ye.png', 'active'),
  ('Zambia', 'https://flagcdn.com/w80/zm.png', 'active'),
  ('Zimbabwe', 'https://flagcdn.com/w80/zw.png', 'active')
on conflict (name) do update set flag_url = excluded.flag_url;

notify pgrst, 'reload schema';
